### ISSUE TITLE
SGCT setup instructions

### ISSUE THREAD

**Issue by eriksunden** [opensgct/sgct#1]
Should maybe include install and conf of NASM?

**Comment by miroandel** [comment]
Might be good in some cases but nasm is part of some unix based operation
systems. This is causing problems in OS X where the OS is using a very old
version of nasm. Nasm is pretty simple to install on all systems and it's a
hassle to compile it manually. Specially under windows where you need to
use msys + mingw.

2015-09-07 15:48 GMT+02:00 eriksunden <notifications@github.com>:
