### ISSUE TITLE
Add C++11 callbacks for encode and decode in SharedData.

### ISSUE THREAD

**Issue by dasmysh** [opensgct/sgct#11]
The callbacks in `sgct::Engine` all support the C++11 `std::function` interface that allows for using closures as callbacks. This is a great feature when writing object oriented code without global objects or singletons. The callbacks in `sgct::SharedData` break that pattern by allowing only C function pointers.

I'd be willing to create a pull request for that feature if necessary.

**Comment by eriksunden** [comment]
Sorry for the incredible late reply, but yes, if you still want to contribute with this feature it would be of interest, as we just made a permanent switch to minimum c++11 (something that obviously should have been done long ago).
