### ISSUE TITLE
Error in tinythread.h: ‘volatile bool*’ is incompatible with argument 1 of ‘__sync_add_and_fetch’...

### ISSUE THREAD

**Issue by emiax** [opensgct/sgct#14]
When compiling sgct on Ubuntu 17.04 with gcc 6.3.0, the following error is generated:

```
from sgct/src/sgct/MessageHandler.cpp:8:
/sgct/include/external/tinythread.h: In instantiation of ‘T tthread::atomic<T>::load(tthread::memory_order) const [with T = bool]’:
/sgct/src/sgct/MessageHandler.cpp:305:27:   required from here
/sgct/include/external/tinythread.h:698:34: error: operand type ‘volatile bool*’ is incompatible with argument 1 of ‘__sync_add_and_fetch’
       return __sync_add_and_fetch((volatile T*)&mValue, 0);
```

I fixed this locally by changing all `tthread::atomic` to `std::atomic`. Is anyone aware of why this happens? Possible solution: drop tinythread dependency and use std::thread instead.

**Comment by patlj09** [comment]
Can you go with C++11 as minimum level, stick with std::thread. Just my two cents.

Best regards,
Patric

On 16 May 2017, at 14:22, Emil Axelsson <notifications@github.com<mailto:notifications@github.com>> wrote:


When compiling sgct on Ubuntu 17.04 with gcc 6.3.0, the following error is generated:

from sgct/src/sgct/MessageHandler.cpp:8:
/sgct/include/external/tinythread.h: In instantiation of ‘T tthread::atomic<T>::load(tthread::memory_order) const [with T = bool]’:
/sgct/src/sgct/MessageHandler.cpp:305:27:   required from here
/sgct/include/external/tinythread.h:698:34: error: operand type ‘volatile bool*’ is incompatible with argument 1 of ‘__sync_add_and_fetch’
       return __sync_add_and_fetch((volatile T*)&mValue, 0);


I fixed this locally by changing all tthread::atomic to std::atomic. Is anyone aware of why this happens? Possible solution: drop tinythread dependency and use std::thread instead.

**Comment by alexanderbock** [comment]
I agree... changing to C++11 (or higher) would be better.  @miroandel ?

**Comment by emiax** [comment]
Just looked at this toady again. Commenting this makes it compile (in `tinythread.h`). Not sure what other implications it has though.

```
// Do we have atomic builtins?
#if defined(__GNUC__) && defined(__GNUC_MINOR__) && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 1))
#define _TTHREAD_HAS_ATOMIC_BUILTINS_
#endif
```

**Comment by alexanderbock** [comment]
For testing, there is a branch `C++11` that removes tinythread and uses std::thread instead

**Comment by eriksunden** [comment]
I have gone over the c++11 branch with all examples and removed all reference and files related to tinythread completely. As such, the jenkins system is now building the c++11 branch, as I also agree this branch should become master asap, if no-one has strong objections?

**Comment by alexanderbock** [comment]
Definitely not ...  there are a couple of more changes (removing dependencies) that can occur once we are limited to modern C++

**Comment by eriksunden** [comment]
Miro was cool with it.
c++11 branch has now been merged into master (created a c++99 branch before the merge, just for reference when the change was made).
