### ISSUE TITLE
Update glm (and I guess all of your dependencies)

### ISSUE THREAD

**Issue by einsweniger** [opensgct/sgct#17]
So, I've been compiling this with a recent compiler (7.2.0). Not sure if that has anything to do with it; but I can confirm several glm related bugs that went away after updating it to v0.9.5.3-626-g8f39bb87.
One is as severe as subtracting two vec2<float> from another and receiving a *completely* wrong result.
The other is: glm::value_ptr returns wrong addresses.

As already mentioned (in issue #13): migrating your dependencies to submodules should help a lot.

**Comment by einsweniger** [comment]
Ignore this issue for now. I'm still trying to figure out the problem. User error is still possible.

**Comment by alexanderbock** [comment]
Thanks for the feedback!

In an unrelated matter:   Great user name!   I honestly thought my mail program was broken and was displaying a faulty index when I saw "-1"

**Comment by einsweniger** [comment]
I've tried several versions of glm now, the one mentioned above works for me. All others (including the recent stable) have errors when running the test suite.
I've narrowed it down to either a bug in glm or my compiler: the results are calculated correctly until finally the wrong memory location is passed back to my code. All that on a (seemingly?) simple subtraction. Although I'd like to report upstream, I should not put more time into that.

PS: Yea, my username has puzzled many others :D

**Comment by alexanderbock** [comment]
Mhh...  I have had weird errors with glm before where it was using a weird internal memory layout, so I wouldn't be too surprised.   It might also be a conflict between two GLM versions if some other library is using GLM as well..  

Thanks for bringing it up;  i'll investigate it on our end as well
