### ISSUE TITLE
SGCT CMake app configuration

### ISSUE THREAD

**Issue by eriksunden** [opensgct/sgct#2]
Should probably include more FindSGCT functionality and every project should include "-config "$SGCT_ROOT_DIR}/config/single.xml"" and the correct working directory (for instance as some projects load images etc).

**Comment by miroandel** [comment]
How do you do that? For visual studio that info is not stored in the
project file but in the user file. Might be possible in xcode to predefine
schemes but not sure how to do that in cmake.

2015-09-07 15:51 GMT+02:00 eriksunden <notifications@github.com>:

**Comment by eriksunden** [comment]
Hmm... then let's skip this then and make a nice examplelauncher which lists all available examples against all config files then :+1: , such that you quickly can try different combinations?

**Comment by eriksunden** [comment]
The separate script files (.bat etc) is good (for now ;D). So closing this issue/discussion.

**Comment by alexanderbock** [comment]
I think that if no -config option is specified, it should automatically use a default single.xml that can be encoded in the source code. I think having to specify a single.xml that is the same in almost all test cases anyway is not very useful.
