### ISSUE TITLE
Change CMakeLists.txt to support future compilers.

### ISSUE THREAD

**Issue by dasmysh** [opensgct/sgct#27]
Currently (at least for the windows build) the CMake will fail on newer Visual Studio versions that are not currently in your list (see https://github.com/opensgct/sgct/blob/54f917a88203592f8b3389333a042b256ae6c9cf/CMakeLists.txt#L89 and following lines).

I suggest setting the necessary variables in a more stable way:

```[..]
elseif( MSVC )
  set(SGCT_COMPILER "msvc${MSVC_TOOLSET_VERSION}")

  if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(SGCT_ARCHITECTURE "x64")
    set(SGCT_LIB_PATH "${SGCT_TARGET_PATH}/lib/${SGCT_COMPILER}_x64")
    set(SGCT_LIB_SRC_PATH "${PROJECT_SOURCE_DIR}/lib/${SGCT_COMPILER}_x64")
  else()
    set(SGCT_ARCHITECTURE "x86")
    set(SGCT_LIB_PATH "${SGCT_TARGET_PATH}/lib/${SGCT_COMPILER}")
    set(SGCT_LIB_SRC_PATH "${PROJECT_SOURCE_DIR}/lib/${SGCT_COMPILER}")
  endif()
elseif( UNIX AND NOT APPLE )
[..]
```

The naming scheme will be slightly different (for newer versions of VS that is) but also more consistent with Microsofts versioning of their compilers (which differs from the VS version number) which I believe is the more relevant number anyways:

- 'msvc15' -> 'msvc141'
- 'msvc16' (assumed you will call the VS2019 version that way) ->'msvc142'

Also: less code :)

**Comment by alexanderbock** [comment]
Fixed in the new `master` branch that got rid of all of this code.  Thanks for reporting the issue!
