### ISSUE TITLE
File permissions on merge_libs_xcode.sh.in

### ISSUE THREAD

**Issue by EricMyers47** [opensgct/sgct#7]
The script merge_libs_xcode.sh run at post-build needs to executable.   Since it is created by CMake from merge_libs_xcode.sh.in the file permissions on that latter file need to set the executable bit (basically chmod +x the file and commit that change)

**Comment by EricMyers47** [comment]
There are actually two such files, one in lib/mac/ and the other in lib/mac_cpp11/

**Comment by alexanderbock** [comment]
Fixed in the new `master` as this file no longer exists

**Comment by EricMyers** [comment]
Finally!  :-)
